# Generated by Django 4.0.5 on 2022-07-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('Ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicacion')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.categoria')),
            ],
        ),
    ]
